require_relative './errors/incorrect_attribute_type_error'
require_relative './errors/incorrect_attribute_value_error'
require_relative './errors/unknown_entity_class_error'

require_relative './validation/validation'
require_relative './entities/author'
require_relative './entities/book'
require_relative './entities/address'
require_relative './entities/reader'
require_relative './entities/order'
require_relative './entities/library'

require_relative './file_encoder/yaml_encoder'
require_relative './statistic/statistic'
require_relative './faker/faker'
